version: '3.8'

volumes:
    pinchi_data: {}

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: /app/scripts/start.sh
    entrypoint: /app/scripts/entrypoint.sh
    restart: on-failure
    env_file: .env

  frontend:
    image: node:10-alpine
    command: npm run serve
    volumes:
      - ./.env:/app/.env:ro
      - ./frontend:/app
    working_dir: /app
    restart: on-failure

  postgres:
    image: postgres:14-alpine
    volumes:
      - pinchi_data:/var/lib/postgresql/data
    env_file: .env

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: none
